spring: 
  jpa:
    database: h2
    generate-ddl: true
    properties: 
      hibernate: 
        show_sql: false 
        format_sql: true    database-platform: org.hibernate.dialect.H2Dialect
  datasource:    type: com.zaxxer.hikari.HikariDataSource    url: jdbc:h2:mem:test    username: sa
    password:  h2:    console:
      path: /h2
     
server:  port: 9999
  
